"""add denomination table

Revision ID: 2fc12ca49e6
Revises: 38c4e85512a9
Create Date: 2016-01-13 16:29:04.290602

"""

# revision identifiers, used by Alembic.
revision = '2fc12ca49e6'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unipin_denomination',
    sa.Column('iID', sa.Integer(), nullable=False),
    sa.Column('cdCode', sa.String(length=8), nullable=False),
    sa.Column('amtUC', sa.Integer(), nullable=False),
    sa.Column('amtRP', sa.Integer(), nullable=False),
    sa.Column('szDescription', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('iID')
    )
    op.create_index('ix_unipin_denomination_cdCode', 'unipin_denomination', ['cdCode'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unipin_denomination_cdCode', 'unipin_denomination')
    op.drop_table('unipin_denomination')
    ### end Alembic commands ###
